#!/usr/bin/env python3
"""
Run chunk-size/overlap ablation correctly.

For every configuration:
1. Set CHUNK_SIZE and CHUNK_OVERLAP.
2. Start a fresh Flask application.
3. Wait until the application is ready.
4. Run run_full_ablation.py.
5. Stop the application.
6. Repeat with the next configuration.

This ensures the document chunks and FAISS index are rebuilt
for every chunk-size setting.
"""

import os
import sys
import time
import socket
import subprocess


# ---------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------

configs = [
    {"chunk_size": 250, "chunk_overlap": 50},
    {"chunk_size": 500, "chunk_overlap": 100},   # current default
    {"chunk_size": 750, "chunk_overlap": 150},
    {"chunk_size": 1000, "chunk_overlap": 200},
]

# Change this only if your Flask application has another filename
APP_FILE = "newapp.py"

HOST = "127.0.0.1"
PORT = 5000

STARTUP_TIMEOUT = 120


# ---------------------------------------------------------
# HELPER: wait until Flask port is available
# ---------------------------------------------------------

def wait_for_server(host, port, timeout=120):
    print(f"Waiting for application on {host}:{port} ...")

    start = time.time()

    while time.time() - start < timeout:
        try:
            with socket.create_connection((host, port), timeout=2):
                print("Application is ready.")
                return True
        except OSError:
            time.sleep(2)

    return False


# ---------------------------------------------------------
# RUN EACH CHUNK CONFIGURATION
# ---------------------------------------------------------

for cfg in configs:

    chunk_size = cfg["chunk_size"]
    chunk_overlap = cfg["chunk_overlap"]

    print("\n" + "=" * 70)
    print(
        f"RUNNING CHUNK ABLATION: "
        f"chunk_size={chunk_size}, overlap={chunk_overlap}"
    )
    print("=" * 70)

    # Create environment specifically for this run
    env = os.environ.copy()

    env["CHUNK_SIZE"] = str(chunk_size)
    env["CHUNK_OVERLAP"] = str(chunk_overlap)

    # Do not allow an old fusion experiment setting to interfere
    env.pop("FUSION_WEIGHTS", None)

    # -----------------------------------------------------
    # START FRESH APPLICATION
    # -----------------------------------------------------

    print(
        f"\nStarting {APP_FILE} with "
        f"CHUNK_SIZE={chunk_size}, "
        f"CHUNK_OVERLAP={chunk_overlap}"
    )

    app_process = subprocess.Popen(
        [sys.executable, APP_FILE],
        env=env
    )

    try:

        # Wait for Flask application to initialize
        if not wait_for_server(HOST, PORT, STARTUP_TIMEOUT):

            print(
                f"ERROR: Application failed to start for "
                f"{chunk_size}/{chunk_overlap}"
            )

            app_process.terminate()
            app_process.wait()

            continue

        # Give FAISS / embeddings a little extra time
        time.sleep(3)

        # -------------------------------------------------
        # RUN ABLATION
        # -------------------------------------------------

        print(
            f"\nRunning 60-query evaluation for "
            f"{chunk_size}/{chunk_overlap}"
        )

        result = subprocess.run(
            [sys.executable, "run_full_ablation.py"],
            env=env
        )

        if result.returncode != 0:
            print(
                f"WARNING: run_full_ablation.py failed for "
                f"{chunk_size}/{chunk_overlap}"
            )
        else:
            print(
                f"Completed chunk configuration "
                f"{chunk_size}/{chunk_overlap}"
            )

    finally:

        # -------------------------------------------------
        # STOP APPLICATION BEFORE NEXT CONFIGURATION
        # -------------------------------------------------

        print("\nStopping application...")

        app_process.terminate()

        try:
            app_process.wait(timeout=15)
        except subprocess.TimeoutExpired:
            print("Application did not stop cleanly. Killing it.")
            app_process.kill()
            app_process.wait()

        # Allow port 5000 to become free
        time.sleep(3)


print("\n" + "=" * 70)
print("CHUNK ABLATION FINISHED")
print("=" * 70)

print(
    "Results should be in full_ablation_results.csv "
    "or the output file generated by run_full_ablation.py."
)